source 'https://rubygems.org'

gem 'berkshelf',          '>= 3.2.3'
gem 'chef',               '>= 12.1'
gem 'chefspec'
gem 'foodcritic',         '>= 3.0'
gem 'rake'
gem 'strainer'
gem 'rubocop'
gem 'test-kitchen',       '>= 1.2.1'
gem 'kitchen-vagrant'
